/** A polished sample investigation dataset used whenever live workspace data is unavailable. */

import {
  buildDashboardStats,
  buildDependencyGraph,
  buildIncidentTimeline,
  buildPostmortemSummary,
} from "@/lib/insights";
import type {
  AnalysisFinding,
  AnalysisHealthScore,
  AnalysisIncident,
  BackendHealthResponse,
  BackendMode,
  BackendReadyResponse,
  InvestigationBundle,
} from "@/lib/types";

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

const demoHealth: BackendHealthResponse = {
  status: "ok",
  service: "nexusai-api",
  version: "0.1.0",
  environment: "demo",
  telemetry: "local-observability",
};

const demoReady: BackendReadyResponse = {
  status: "ready",
  service: "nexusai-api",
  database: {
    status: "ready",
    checked_at: minutesAgo(8),
  },
  adapters: [
    {
      source_type: "sample",
      display_name: "Sample workspace",
      status: "ready",
      deployment_model: "free-local",
      description: "Offline sample payloads used to exercise the workspace without external accounts.",
    },
    {
      source_type: "otlp",
      display_name: "Local intake",
      status: "ready",
      deployment_model: "free-local",
      description: "Signals accepted locally and normalized into the shared contract.",
    },
    {
      source_type: "cloudwatch",
      display_name: "Future cloud source",
      status: "planned",
      deployment_model: "future-external",
      description: "Future connector behind the adapter seam.",
    },
    {
      source_type: "openobserve",
      display_name: "Future review source",
      status: "planned",
      deployment_model: "future-external",
      description: "Future connector behind the adapter seam.",
    },
  ],
};

const demoFindings: AnalysisFinding[] = [
  {
    id: "finding-latency-001",
    tenant_id: "platform-demo",
    incident_id: "incident-latency-spike",
    telemetry_signal_id: "sig-latency-001",
    correlation_key: "platform-demo|checkout-api|checkout-burst",
    source_name: "local-otel-collector",
    source_type: "otlp",
    observed_at: hoursAgo(3.2),
    batch_label: "checkout-burst",
    category: "performance",
    kind: "metric",
    severity: "critical",
    title: "Checkout p95 latency breached the response budget",
    summary: "The checkout path crossed the 900ms p95 threshold while queue depth and cache misses both increased.",
    confidence: 0.96,
    evidence: { threshold: "900ms p95", current: "1.4s", delta: "+55%" },
    recommendations: ["Scale the checkout worker pool", "Inspect cache hit rate and database wait time"],
    service_name: "checkout-api",
    workload_name: "checkout-web",
    cluster_name: "prod-cluster-a",
    namespace: "payments",
    created_at: hoursAgo(3.1),
  },
  {
    id: "finding-queue-002",
    tenant_id: "platform-demo",
    incident_id: "incident-latency-spike",
    telemetry_signal_id: "sig-queue-002",
    correlation_key: "platform-demo|payments-worker|checkout-burst",
    source_name: "local-otel-collector",
    source_type: "otlp",
    observed_at: hoursAgo(3.05),
    batch_label: "checkout-burst",
    category: "reliability",
    kind: "event",
    severity: "error",
    title: "Queue processing lagged behind incoming checkout traffic",
    summary: "Message age rose steadily and the worker backlog kept expanding during the same window as the latency spike.",
    confidence: 0.88,
    evidence: { backlog: 214, processed_per_minute: 112 },
    recommendations: ["Check worker autoscaling triggers", "Inspect retries and downstream timeouts"],
    service_name: "payments-worker",
    workload_name: "checkout-jobs",
    cluster_name: "prod-cluster-a",
    namespace: "payments",
    created_at: hoursAgo(3),
  },
  {
    id: "finding-cache-003",
    tenant_id: "platform-demo",
    incident_id: "incident-cache-thrash",
    telemetry_signal_id: "sig-cache-003",
    correlation_key: "platform-demo|redis-cache|cache-thrash",
    source_name: "local-otel-collector",
    source_type: "otlp",
    observed_at: hoursAgo(6.4),
    batch_label: "cache-thrash",
    category: "performance",
    kind: "metric",
    severity: "warning",
    title: "Cache hit ratio fell below the steady-state target",
    summary: "Redis read amplification and a spike in invalidations made the cache less effective than usual.",
    confidence: 0.81,
    evidence: { hit_ratio: "72%", misses: 188 },
    recommendations: ["Review invalidation policy", "Confirm hot-key distribution"],
    service_name: "redis-cache",
    workload_name: "cache-layer",
    cluster_name: "prod-cluster-a",
    namespace: "platform",
    created_at: hoursAgo(6.2),
  },
  {
    id: "finding-auth-004",
    tenant_id: "platform-demo",
    incident_id: "incident-auth-degrade",
    telemetry_signal_id: "sig-auth-004",
    correlation_key: "platform-demo|auth-service|auth-spike",
    source_name: "local-otel-collector",
    source_type: "otlp",
    observed_at: hoursAgo(1.1),
    batch_label: "auth-spike",
    category: "security",
    kind: "alert",
    severity: "warning",
    title: "Authentication requests showed a burst of denied attempts",
    summary: "The denial rate climbed quickly, but the guardrail rules kept the event understandable and contained.",
    confidence: 0.78,
    evidence: { denied_rate: "18%", burst_window: "12m" },
    recommendations: ["Validate login throttling", "Review the suspicious request origin"],
    service_name: "auth-service",
    workload_name: "identity-api",
    cluster_name: "prod-cluster-b",
    namespace: "platform",
    created_at: hoursAgo(1),
  },
];

const demoIncidents: AnalysisIncident[] = [
  {
    id: "incident-latency-spike",
    tenant_id: "platform-demo",
    correlation_key: "platform-demo|checkout-api|checkout-burst",
    scope_kind: "service",
    scope_name: "checkout-api",
    state: "investigating",
    title: "Checkout latency spike is cascading into the payment path",
    summary: "The checkout service is slower than budget, and the queue worker evidence suggests a downstream saturation pattern.",
    probable_cause: "Likely worker saturation combined with cache churn and slower write amplification.",
    confidence: 0.96,
    evidence_count: 2,
    finding_count: 2,
    recommendations: ["Scale the worker pool", "Inspect cache hit rate", "Review database commit latency"],
    service_name: "checkout-api",
    workload_name: "checkout-web",
    cluster_name: "prod-cluster-a",
    namespace: "payments",
    created_at: hoursAgo(3.1),
    updated_at: hoursAgo(1.5),
    resolved_at: null,
    evidence: demoFindings.filter((finding) => finding.incident_id === "incident-latency-spike").map((finding) => ({
      finding_id: finding.id,
      telemetry_signal_id: finding.telemetry_signal_id,
      title: finding.title,
      summary: finding.summary,
      category: finding.category,
      severity: finding.severity,
      confidence: finding.confidence,
    })),
  },
  {
    id: "incident-cache-thrash",
    tenant_id: "platform-demo",
    correlation_key: "platform-demo|redis-cache|cache-thrash",
    scope_kind: "service",
    scope_name: "redis-cache",
    state: "acknowledged",
    title: "Cache churn is reducing the effectiveness of the shared cache layer",
    summary: "The cache service is still healthy enough to serve requests, but the hit ratio erosion is large enough to watch.",
    probable_cause: "Invalidation patterns are creating more write pressure than the cache can absorb efficiently.",
    confidence: 0.81,
    evidence_count: 1,
    finding_count: 1,
    recommendations: ["Review invalidation policy", "Check for hot-key skew"],
    service_name: "redis-cache",
    workload_name: "cache-layer",
    cluster_name: "prod-cluster-a",
    namespace: "platform",
    created_at: hoursAgo(6.2),
    updated_at: hoursAgo(4.8),
    resolved_at: null,
    evidence: demoFindings.filter((finding) => finding.incident_id === "incident-cache-thrash").map((finding) => ({
      finding_id: finding.id,
      telemetry_signal_id: finding.telemetry_signal_id,
      title: finding.title,
      summary: finding.summary,
      category: finding.category,
      severity: finding.severity,
      confidence: finding.confidence,
    })),
  },
  {
    id: "incident-auth-degrade",
    tenant_id: "platform-demo",
    correlation_key: "platform-demo|auth-service|auth-spike",
    scope_kind: "service",
    scope_name: "auth-service",
    state: "resolved",
    title: "Authentication spike has been contained",
    summary: "The identity path experienced a burst of denied attempts, but the system remained operational and the event was resolved quickly.",
    probable_cause: "Likely scripted retry traffic or a misconfigured client during a deployment window.",
    confidence: 0.79,
    evidence_count: 1,
    finding_count: 1,
    recommendations: ["Monitor client retry behavior", "Keep the throttle policy in place"],
    service_name: "auth-service",
    workload_name: "identity-api",
    cluster_name: "prod-cluster-b",
    namespace: "platform",
    created_at: hoursAgo(1.1),
    updated_at: minutesAgo(22),
    resolved_at: minutesAgo(22),
    evidence: demoFindings.filter((finding) => finding.incident_id === "incident-auth-degrade").map((finding) => ({
      finding_id: finding.id,
      telemetry_signal_id: finding.telemetry_signal_id,
      title: finding.title,
      summary: finding.summary,
      category: finding.category,
      severity: finding.severity,
      confidence: finding.confidence,
    })),
  },
];

const demoHealthScores: AnalysisHealthScore[] = [
  {
    scope_kind: "service",
    scope_name: "checkout-api",
    score: 41,
    status: "critical",
    finding_count: 2,
    incident_count: 1,
    last_seen_at: hoursAgo(1.5),
    primary_reason: "Latency, backlog, and cache churn are compounding.",
  },
  {
    scope_kind: "service",
    scope_name: "redis-cache",
    score: 67,
    status: "watch",
    finding_count: 1,
    incident_count: 1,
    last_seen_at: hoursAgo(4.8),
    primary_reason: "Lower hit rate and invalidations deserve attention.",
  },
  {
    scope_kind: "service",
    scope_name: "auth-service",
    score: 88,
    status: "healthy",
    finding_count: 1,
    incident_count: 1,
    last_seen_at: minutesAgo(22),
    primary_reason: "The denial burst is resolved and the service is stable.",
  },
  {
    scope_kind: "workload",
    scope_name: "payments-worker",
    score: 52,
    status: "degraded",
    finding_count: 1,
    incident_count: 1,
    last_seen_at: hoursAgo(3),
    primary_reason: "The queue backlog is still above normal operating levels.",
  },
];

const demoBundle = {
  graph: buildDependencyGraph(demoIncidents, demoHealthScores),
  postmortem: buildPostmortemSummary(demoIncidents, demoFindings),
};

export function buildDemoInvestigationBundle(mode: BackendMode = "demo"): InvestigationBundle {
  return {
    mode,
    generatedAt: new Date().toISOString(),
    sourceLabel: "Sample workspace data",
    sourceReason: "Live data was empty or unavailable, so a curated workspace story is shown instead.",
    backendHealth: demoHealth,
    backendReady: demoReady,
    findings: demoFindings,
    incidents: demoIncidents.map((incident) => ({
      ...incident,
      evidence: incident.evidence,
    })),
    healthScores: demoHealthScores,
    graph: demoBundle.graph,
    postmortem: {
      ...demoBundle.postmortem,
      sections: demoBundle.postmortem.sections,
      action_items: demoBundle.postmortem.action_items,
    },
    stats: buildDashboardStats(demoFindings, demoIncidents, demoHealthScores),
  };
}

export function enrichIncidentBundle(incident: AnalysisIncident, findings: AnalysisFinding[]) {
  return {
    incident,
    timeline: buildIncidentTimeline(incident),
    postmortem: buildPostmortemSummary([incident], findings),
  };
}
